### ISSUE TITLE
20w11a Opening Cooking Table

### ISSUE THREAD

**Issue by ghost** [CottonMC/EpicureanGastronomy#28]
Crash on open GUI of Cooking Table

`---- Minecraft Crash Report ----
// Don't do that.

Time: 3/13/20 12:41 PM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraft.class_1657.method_5704()Lnet/minecraft/class_2338;
	at io.github.cottonmc.epicurean.container.CookingTableContainer.<init>(CookingTableContainer.java:32)
	at io.github.cottonmc.epicurean.container.CookingTableScreen.<init>(CookingTableScreen.java:18)
	at io.github.cottonmc.epicurean.EpicureanClient.lambda$onInitializeClient$0(EpicureanClient.java:20)
	at io.github.cottonmc.epicurean.EpicureanClient$$Lambda$1920/725736615.create(Unknown Source)
	at net.fabricmc.fabric.impl.client.container.ScreenProviderRegistryImpl.lambda$null$1(ScreenProviderRegistryImpl.java:85)
	at net.fabricmc.fabric.impl.client.container.ScreenProviderRegistryImpl$$Lambda$4481/75192843.run(Unknown Source)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.class_1255.method_5383(class_1255.java:103)
	at net.minecraft.class_310.method_1523(class_310.java:970)
	at net.minecraft.class_310.method_1514(class_310.java:631)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at io.github.cottonmc.epicurean.container.CookingTableContainer.<init>(CookingTableContainer.java:32)
	at io.github.cottonmc.epicurean.container.CookingTableScreen.<init>(CookingTableScreen.java:18)
	at io.github.cottonmc.epicurean.EpicureanClient.lambda$onInitializeClient$0(EpicureanClient.java:20)
	at io.github.cottonmc.epicurean.EpicureanClient$$Lambda$1920/725736615.create(Unknown Source)
	at net.fabricmc.fabric.impl.client.container.ScreenProviderRegistryImpl.lambda$null$1(ScreenProviderRegistryImpl.java:85)
	at net.fabricmc.fabric.impl.client.container.ScreenProviderRegistryImpl$$Lambda$4481/75192843.run(Unknown Source)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)

-- Affected level --
Details:
	All players: 1 total; [class_746['ScarlettBlade'/1, l='MpServer', x=-204.27, y=4.00, z=132.82]]
	Chunk stats: Client Chunk Cache: 841, 529
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 4697988257341606882
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: NBT[{}]
	Level spawn location: World: (-208,4,128), Chunk: (at 0,0,0 in -13,8; contains blocks -208,0,128 to -193,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 298 game time, 298 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:431)
	at net.minecraft.class_310.method_1587(class_310.java:1966)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 20w11a
	Minecraft Version ID: 20w11a
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 630380608 bytes (601 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 1.2.4
		betternether: Better Nether 2.4.0
		blast: BLAST 1.2
		blue_endless_jankson: jankson +
		cardinal-components-base: Cardinal Components API 2.3.0
		cardinal-components-entity: Cardinal Components API 2.3.0
		cloth: Cloth Events 2.0.0-unstable.202003051905
		cloth-basic-math: Cloth Basic Math 0.4.1
		cloth-config2: Cloth Config v2 3.0.2-unstable.202003090708
		cotton: Cotton 1.0.2
		cotton-cauldron: Cotton Cauldron 1.0.0-rc.6
		cotton-commons: Cotton Commons 1.0.0-rc.4
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-datapack: Cotton Datapack 1.0.1
		cotton-logging: Cotton Logging 1.0.0-rc.4
		cotton-player-events: Cotton Player Events 1.0.2
		creativebuttonmover: Creative Button Mover 0.2.0+20w10a
		darkness: True Darkness 1.3.24
		diggusmaximus: Diggus Maximus 1.2.6
		epicurean: Epicurean 2.2.4+1.15.2
		expandedstorage: ExpandedStorage 4.12.39+20w10a
		expandedstorageapi: ExpandedStorageAPI 0.0.6+20w10a
		fabric: Fabric API 0.5.3+build.308-1.16
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d3d
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.1+b7d52fa53d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea893d
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.6+0aae0f413d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d3d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3d
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+b17265713d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+04b997943d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825d3d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.9+5b8a535a3d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d63d
		fabric-language-kotlin: Fabric Language Kotlin 1.3.61+build.1
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.6+2f56dff23d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+5b8a535a3d
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d63d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.4+9421522d3d
		fabric-networking-v0: Fabric Networking (v0) 0.1.8+9421522d3d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.4+b7d52fa53d
		fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d63d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.7+9421522d3d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.11+2f56dff23d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.25+2f56dff23d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a603d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d3d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed93d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104903d
		fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+534104903d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.12+5b8a535a3d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915803d
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba73d
		fabricloader: Fabric Loader 0.7.8+build.187
		fairenchanting: FairEnchanting 1.1.2
		flax: Flax 1.1.1
		glassdoor: Glass Doors 1.4.3
		illuminations: Illuminations 0.6
		jankson: Jankson 2.0.1+j1.2.0
		libcd: LibCapableData 2.2.2+1.15.2
		lightoverlay: Light Overlay 5.0-unstable.202003090635
		me_shedaniel_cloth_basic-math: basic-math 0.3.0
		minecraft: Minecraft 1.16-alpha.20.11.a
		ml3api: ML3API 1.3.1
		modmenu: Mod Menu 1.10.2+build.1
		ninjaphenix-container-lib: NinjaPhenix's Container Library 0.1.8+20w10a
		okzoomer: Ok Zoomer 3.0.0
		orderly: Orderly 2.0.0-alpha-8-1.16
		org_jetbrains_annotations: annotations 18.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.61
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.61
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.61
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.61
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.3
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.3
		phosphor: Phosphor 0.4.2
		roughlyenoughitems: Roughly Enough Items 4.0.12-unstable
		terraform: Terraform 1.5.2+build.5
		the_bumblezone: The Bumblezone - Fabric 1.0.2-20w10a
		traverse: Traverse 2.2.1+build.3
		vanilla-hammers: Vanilla Hammers 1.7.0
		water-erosion: Water Erosion 1.0.2
	Launched Version: fabric-loader-0.7.8+build.187-20w11a
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 980/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.12, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Nate's+Tweaks+0.34+1.15-1.16.zip
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor `

**Comment by LemmaEOF** [comment]
Yep, Mojang broke all GUIs *again* in 20w10a and above. I’ll push a new build when I’ve got the time.

**Comment by i509VCB** [comment]
@Ninonsand for more context, all mods that have GUIs broke since realms has become part of the minecraft jar in 20w11a rather than a separate library. And of course the names it uses are now obfuscated.
